#cource 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
#cource 'ssh://git@10.54.147.91:5522/root/ios_podspecs.git'
use_frameworks!

platform :ios, '9.3'

target 'votcircleslide_Example' do
  pod 'votcircleslide', :path => '../'

  target 'votcircleslide_Tests' do
    inherit! :search_paths

    
  end
end
